% Produced by CVXGEN, 2017-09-04 14:14:14 -0400.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
FMAX = params.FMAX;
FMIN = params.FMIN;
W_row2 = params.W_row2;
W_row3 = params.W_row3;
W_row4 = params.W_row4;
wdes = params.wdes;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable f(4, 1);

  minimize(norm(W_row3'*f - wdes(3), 1));
  subject to
    sum(f) == wdes(1);
    W_row2'*f == wdes(2);
    W_row4'*f == wdes(4);
    FMIN <= f;
    f <= FMAX;
cvx_end
vars.f = f;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
