// Author: Zijian Wang, Stanford University
// Date: Jul 12, 2017
// zjwang@stanford.edu

#include "diff2SttInC.h"
#include "quadDef.h"
#include "stdio.h"
#include "dMath.h"
#include "diffMath.h"

int main(void) {
    printf("Differential flatness test program.\n");
    
    // output
    States state;
    Inputs input;
    double ** Rd1;
    double ** Rd2;
    double * wbd1;
    double * euler; 
    double * eulerd1;
    double * eulerd2;
    // input
    Params param;
    FlatOut flatout;

    // allocate memories for output pointers
    state.v = (double *)malloc(3 * sizeof(double));
    state.R = (double **)malloc(3 * sizeof(double*));
    state.wb = (double *)malloc(3 * sizeof(double));
    state.h = (double *)malloc(3 * sizeof(double));

    input.tau = (double *)malloc(3 * sizeof(double));

    Rd1 = (double **)malloc(3 * sizeof(double*));
    Rd2 = (double **)malloc(3 * sizeof(double*));
    for(int i=0; i<3; i++) {
        Rd1[i] = (double*)malloc(3 * sizeof(double));
        Rd2[i] = (double*)malloc(3 * sizeof(double));
        state.R[i] = (double*)malloc(3 * sizeof(double));
    }
    wbd1 = (double *)malloc(3 * sizeof(double));
    euler = (double *)malloc(3 * sizeof(double));
    eulerd1 = (double *)malloc(3 * sizeof(double));
    eulerd2 = (double *)malloc(3 * sizeof(double));

    // initialize Params
    param.J = (double**)malloc(3 * sizeof(double*));
    param.invJ = (double**)malloc(3 * sizeof(double*));
    for(int i=0; i<3; i++){
        param.J[i] = (double*)malloc(3 * sizeof(double));
        param.invJ[i] = (double*)malloc(3 * sizeof(double));
    }

    param.J[0][0] = 1.0/6.0;
    param.J[1][1] = 1.0/6.0;
    param.J[2][2] = 1.0/3.0;
    param.invJ[0][0] = 1.0/param.J[0][0];
    param.invJ[1][1] = 1.0/param.J[1][1];
    param.invJ[2][2] = 1.0/param.J[2][2];
    param.m = 2.0;

    // initialize FlatOut
    flatout.sig = (double*)malloc(4 * sizeof(double));
    flatout.sigd1 = (double*)malloc(4 * sizeof(double));
    flatout.sigd2 = (double*)malloc(4 * sizeof(double));
    flatout.sigd3 = (double*)malloc(4 * sizeof(double));
    flatout.sigd4 = (double*)malloc(4 * sizeof(double));

    flatout.sig[0] = 1.0000;
    flatout.sig[1] = 0.0080;
    flatout.sig[2] = -0.5000;
    flatout.sig[3] = 0.0;

    flatout.sigd1[0] = -0.0064;
    flatout.sigd1[1] = 0.8000;
    flatout.sigd1[2] = 0;
    flatout.sigd1[3] = 0;
    
    flatout.sigd2[0] = -0.6400;
    flatout.sigd2[1] = -0.0051;
    flatout.sigd2[2] = 0;
    flatout.sigd2[3] = 0;

    flatout.sigd3[0] = 0.0041;
    flatout.sigd3[1] = -0.5120;
    flatout.sigd3[2] = 0;
    flatout.sigd3[3] = 0;

    flatout.sigd4[0] = 0.4096;
    flatout.sigd4[1] = 0.0033;
    flatout.sigd4[2] = 0;
    flatout.sigd4[3] = 0;

    // do the actual computation
    diff2SttInp(&state, &input, Rd1, Rd2, wbd1,       // output 
                    euler, eulerd1, eulerd2,           // output
                    &param, &flatout);                // input

    // print results
    printf("state.v = %f, %f, %f\n", state.v[0], state.v[1], state.v[2]);
    printf("state.h = %f, %f, %f\n", state.h[0], state.h[1], state.h[2]);
    printf("euler = %f, %f, %f\n", euler[0], euler[1], euler[2]);
    printf("wb = %f, %f, %f\n", state.wb[0], state.wb[1], state.wb[2]);

    // correct output should be: (generated by Matlab)
    // state.v = -0.006400, 0.800000, 0.000000
    // state.h = 1.000000, 0.008000, -0.500000
    // euler = -0.000519, 0.065214, 0.000000
    // wb = -0.052134, -0.000417, -0.000000

    printf("input.fz = %f\n", input.fz);
    printf("input.tau = %f, %f, %f\n", input.tau[0], input.tau[1], input.tau[2]);

    // correct output should be:
    // input.fz = -19.641754
    // input.tau = 0.000056, -0.006936, -0.000014

    return 0;
}