name: ros-build

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    env:
      BASEDIR: /home/runner/work
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      - run: find / -type d -name "test_results" -exec readlink -f {} \; 2>/dev/null
      - uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: /home/runner/work/target_ws/build/test_results/
 

