name: ros-build

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      - run: pwd
      - run: ls
      - run: sudo cd /root/target_ws
      - run: ls
      - run: tree
      - uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: target_ws/build/test_results/
 

